# Generated by Django 5.0.7 on 2024-08-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvariant_sizevarient_products_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color_name',
            field=models.ManyToManyField(blank=True, to='products.colorvariant'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color_size',
            field=models.ManyToManyField(blank=True, to='products.sizevarient'),
        ),
    ]
