# Generated by Django 5.0.7 on 2024-08-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_color_name_alter_products_color_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='color_size',
            new_name='size_variant',
        ),
    ]
